better types
openglobus/openglobus pull request #423
Opened 2021-10-30 14:56 UTC by tbo47

INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE

#### **Verify that...**

- [x] `npm test` passes
- [x] `npm run api` passes
- [x] `npm run lint` passes
- [x] `npm run build` still works

2021-10-31 10:24 UTC, Zemledelec requested changes
Hi @tbo47 lets make type specification in module style as you do, but there is a problem I mentioned in a few comments. Check it out, please. Type specification needs a little more care in a few code files.

2021-10-31 10:24 UTC, Zemledelec commented on src/og/Globe.js
> + * @param {scene.RenderNode} [options.skybox] - Render skybox. null - default.
Not scene.RenderNode but RenderNode

2021-10-31 10:24 UTC, Zemledelec commented on src/og/Globe.js
> + * @param {terrain.Terrain} [options.terrain] - Terrain provider. Default no terrain - og.terrain.EmptyTerrain.
...the same, just EmptyTerrain

2021-10-31 10:24 UTC, Zemledelec commented on src/og/Globe.js
> +             * @type {scene.Planet|og.scene.PlanetAtmosphere}
let's remove PlanetAtmosphere..it was long time ago:)

2021-10-31 10:24 UTC, Zemledelec commented on src/og/camera/Frustum.js
> +     * @param {bv.Sphere} sphere - Bounding sphere.
no bv just Sphere

2021-10-31 19:44 UTC, tbo47 commented on src/og/Globe.js
> + * @param {scene.RenderNode} [options.skybox] - Render skybox. null - default.
done

2021-11-02 17:51 UTC, tbo47 commented
> Hi @tbo47 lets make type specification in module style as you do, but there is a problem I mentioned in a few comments. Check it out, please. Type specification needs a little more care in a few code files.

it's now ready for review

2021-11-03 08:52 UTC, Zemledelec commented on src/og/Globe.js
> +             * @type {Planet|og.scene.PlanetAtmosphere}
Just for future we will remove og.scene.PlanetAtmosphere

2021-11-03 09:14 UTC, Zemledelec approved these changes
@tbo47 I've made a few comments. check it out for future. Looks good! Thanks!

2021-11-03 09:14 UTC, Zemledelec commented on src/og/camera/PlanetCamera.js
> +     * @param {RenderNode} planet - Planet render node.
It's doubled from 21. Looks strange. @tbo47, are you sure, it is correct?

2021-11-03 09:14 UTC, Zemledelec commented on src/og/control/CompassButton.js
> +     * @params {Object} [options] - Control options.
...the same question. When class extends a class parameters are doubled. Is it ok?

2021-11-03 09:14 UTC, Zemledelec commented on src/og/ellipsoid/Ellipsoid.js
> +     * @param {number} equatorialSize - Equatorial ellipsoid size.
May be we have to choose a place where we are going to make description obout constructor options. I prefer any place, but not two places.

2021-11-03 09:14 UTC, Zemledelec commented on src/og/utils/shared.js
> + * @param {math.Vec2} start1 - First line first coordinate.
When we will use this module lets remove math from Vec2. In future. Right now it is ok:)

2021-11-03 09:14 UTC, Zemledelec commented on src/og/scene/Planet.js
> +         * @type {quadTree.Node}
...the same thing, just for future will remove quadTree, and idle etc.

2021-11-03 09:15 UTC, merged