#257 Add geo object and instancing example with low poly 3d objects
openglobus/openglobus pull request #451
Opened 2021-12-16 09:24 UTC by pavletto

Create geo object example with 3d low poly models
Fix instancing in GO. (crack it in #446 :()
Improve performance in recalculating indices! 

#### **Verify that...**

- [ ] `npm test` passes
- [ ] `npm run api` passes
- [ ] `npm run lint` passes
- [ ] `npm run build` still works

2021-12-19 10:45 UTC, Zemledelec requested changes
@pavletto I've made a few comments I think should be improved, or discussed first. Please take a look.

2021-12-19 10:45 UTC, Zemledelec commented on examples/geoObject/geoObject.js
> +const instancesTypes = [...new Array(80).fill('airplane'), ...new Array(20).fill('farmplane'), 'satellite'];
I do not like this iteration logic. I suggest replace it with something more convenient:
```
[
  {
      instanceName: "airplane",
      quantity: 80 
  }, {
      instanceName: "farmplane",
      quantity: 20 
  }.
  ...
]
```

2021-12-19 10:45 UTC, Zemledelec commented on examples/geoObject/geoObject.js
> +    addInstance(type);
In terms of my previous comment, I m afraid that this makes a lot of fetches, no?

2021-12-19 10:45 UTC, Zemledelec commented on src/og/entity/GeoObjectHandler.js
>          this._vertexArr = [-0.5, 0.0, 0.5, -0.5, 0.0, -0.5, 0.5, 0.0, -0.5, 0.5, 0.0, 0.5];
looks like useless code?

2021-12-19 10:45 UTC, Zemledelec commented on src/og/entity/GeoObjectHandler.js
>          this._indicesArr = null;
...this is too

2021-12-20 08:27 UTC, pavletto commented on src/og/entity/GeoObjectHandler.js
>          this._indicesArr = null;
No, is not. `indicesArr` used

2021-12-20 13:45 UTC, pavletto commented
@Zemledelec, I'm resolve

2021-12-23 13:27 UTC, Zemledelec approved these changes

2021-12-23 13:27 UTC, merged