Make webgl1 greate again
openglobus/openglobus pull request #483
Opened 2022-02-08 12:18 UTC by pavletto

Return webgl1 supporting in globus. Add support in instansing. I'm test it in Firefox with disabled webgl2. Don't fix one momet - something wrong with label `a_rotation` in `label` vertexShader. @Zemledelec can you check it please?

2022-03-03 06:53 UTC, yeluoyunfei commented
@pavletto  Just saw this pull request, that's great! is the change ok to merge?

2022-03-29 13:06 UTC, pavletto commented
@Zemledelec ping

2022-03-29 16:22 UTC, Zemledelec commented
> @Zemledelec ping

testing

2022-03-29 16:30 UTC, Zemledelec requested changes

2022-03-29 16:30 UTC, Zemledelec commented on src/og/webgl/Handler.js
> +    isWebGl2() {
Better to make property isWebgl2 right after initialization, and get rid of the method.

2022-03-29 16:30 UTC, Zemledelec commented on src/og/webgl/Handler.js
> +            texture = is2 ? this.createTexture_n_webgl2(imgCnv._canvas) : this.createTexture_n_webgl1(imgCnv._canvas);
Function callbacks should be createTexture_n which assigned during webgl context initialization : createTexture_n = createTexture_n_webgl2

2022-03-29 16:31 UTC, Zemledelec requested changes

2022-03-29 16:31 UTC, Zemledelec commented on src/og/entity/GeoObjectHandler.js
> +                p.drawElementsInstanced(
Better to get rid of if case during webgl context initialization.

2022-03-29 16:33 UTC, Zemledelec commented
need refactor for Program.js
```
    drawElementsInstanced(...args) {
        const gl = this.gl;
        gl.drawElementsInstanced ? gl.drawElementsInstanced(...args) : gl.getExtension('ANGLE_instanced_arrays').drawElementsInstancedANGLE(...args);
    }
```

The idea is not using if case and function call. Instead assign a method to a this.drawElementsInstanced during initialization right inside program

2022-04-12 21:42 UTC, pavletto commented
Check!

2022-04-19 07:08 UTC, Zemledelec approved these changes

2022-04-19 07:13 UTC, Zemledelec commented
Do not forget. I've checked up.

INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE

Verify that...
 npm test passes
 npm run api passes
 npm run lint passes
 npm run build still works

2022-04-19 07:13 UTC, merged