Common worker abstraction
openglobus/openglobus pull request #530
Opened 2022-06-22 12:36 UTC by pavletto

INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE

#### **Verify that...**

- [ ] `npm test` passes
- [ ] `npm run api` passes
- [ ] `npm run lint` passes
- [ ] `npm run build` still works

2022-06-22 14:01 UTC, Zemledelec requested changes

2022-06-22 14:01 UTC, Zemledelec commented on src/og/control/visibleExtent/Segment.js
> +            this.planet._terrainWorker.make({segment, elevations});
dont like instancing.

2022-06-22 14:01 UTC, Zemledelec commented on src/og/entity/LabelHandler.js
> +        this._renderer.labelWorker.make({ handler, label });
the same don't like instancing

2022-06-22 14:01 UTC, Zemledelec commented on src/og/entity/LabelWorker.js
> +    make({ handler, label }) {
There is a IoC possible...thinking...

2022-06-22 14:01 UTC, Zemledelec commented on src/og/entity/LabelWorker.js
> +    make({ handler, label }) {
...maybe it could be refactored in a next iteration

2022-06-22 14:01 UTC, Zemledelec commented on src/og/segment/Segment.js
> +            this.planet._terrainWorker.make({ segment, elevations });
don't like instancing

2022-10-15 07:36 UTC, pavletto commented on src/og/segment/Segment.js
> +            this.planet._terrainWorker.make({ segment, elevations });
fix that

2022-10-15 07:38 UTC, pavletto commented
@Zemledelec check my fixes, please

2022-10-18 11:18 UTC, Zemledelec approved these changes

2022-10-18 11:18 UTC, merged