first working implementation obj supporting
openglobus/openglobus pull request #677
Opened 2023-04-12 12:04 UTC by pavletto

2023-04-12 17:35 UTC, Zemledelec commented on src/og/Object3d.js
> +import { convertToWebGLSpace, objParser } from "./utils/objParser.js";
`transformLeftToRightCoordinateSystem` better

2023-04-12 17:42 UTC, Zemledelec commented on src/og/utils/objParser.js
> +    let webglVertexData = [
no need _webgl_ prefix

2023-04-12 17:52 UTC, Zemledelec requested changes
Change leftToRightCoordinateSystem

2023-04-13 17:31 UTC, pavletto commented on src/og/Object3d.js
> +import { convertToWebGLSpace, objParser } from "./utils/objParser.js";
Fixed

2023-04-13 17:31 UTC, pavletto commented on src/og/utils/objParser.js
> +    let webglVertexData = [
Fixed

2023-04-18 04:56 UTC, Zemledelec approved these changes

2023-04-21 14:29 UTC, pavletto commented
@Zemledelec ready to finish review

2023-04-22 09:53 UTC, Zemledelec approved these changes

2023-04-22 09:55 UTC, merged