Adding event id & added removeEvent functionality
openglobus/openglobus pull request #705
Opened 2023-05-10 19:42 UTC by program-sam

As suggested I added the removeEvent functionality. I did this by allowing for event identifiers, by which events can be searched, and removed again after they are added. I added an example and updated relevant parts of code where events were created, but I did not refactor the entire event design, as that would probably require some more discussion.

what do you think @Zemledelec ?

2023-05-10 19:50 UTC, program-sam commented
I am not really sure what happened in src/og/input/KeyboardHandler.js, why it's all marked as 'changed'

2023-05-13 05:38 UTC, Zemledelec requested changes
1) I think that the better idea is to extract keyboard function for binding in a separate method. For instance onKeyPressed(), onKeyDown et, or` onKey(["pressed", "down", "up"], key code, callback, sender, priority)`.

2) No need ID. Event id is already stamped inside super event stamp methos, I think it is better idea to support off method offKey(callback), because callback already has an id inside __og)stamp__ or something...

2023-05-13 05:38 UTC, Zemledelec commented on src/og/renderer/RendererEvents.js
> +            super.on(name, callback, keyCode, sender);
Third parameter is a sender in the parent class

2023-05-13 05:38 UTC, Zemledelec commented on src/og/renderer/RendererEvents.js
> +            super.on(name, callback, keyCode, sender);
...this is why parameters called p1,p2 etc

2023-05-13 05:42 UTC, Zemledelec commented on src/og/renderer/RendererEvents.js
> +            super.on(name, callback, keyCode, sender);
@program-sam take a look above, I think that the separate keyboard event method convenient way to refactor this "facade"

2023-05-13 05:53 UTC, Zemledelec commented
Just in case, for KeyboardHandler, it would be better not to change all code, because it's hard to review changings :) Just in case, it's a simple module, but for a better experience, I suggest somehow avoiding all code replacing, for example, adding new code in the end...

2023-05-14 19:05 UTC, program-sam commented on src/og/renderer/RendererEvents.js
> +            super.on(name, callback, keyCode, sender);
Ok I get the event ID part. I wasn't aware that these objects were stamped, but that's a really cool implementation! And yes this stamp does remove the need for a custom id, I'll remove those changes.on / off functions for all type of events work, but callbacks are not yet stamped for  "keypress", "charkeypress" and "keyfree" events If i Interpret things correctly? Which is why the off function for keyboard events was not yet implemented? Yes this stamp does remove the need for a custom id, I'll remove those changes.

But for the off function, that requires that you still have a reference to the original callback? The callback that was stamped. In a case like `events.on("keyfree", e => alert('space bar pressed!')` you will lose the reference to the callback function and won't be able to pass it again in the off function right?

I am not really sure what you mean with the idea "to extract keyboard function for binding in a separate method"

2023-05-26 18:19 UTC, Zemledelec commented
I'll try to add what I think about in another branch. It's better to show it in code. 
FYI @program-sam

2023-07-22 09:12 UTC, closed without merging

2023-07-22 09:14 UTC, Zemledelec commented
Replaced to https://github.com/openglobus/openglobus/pull/753